### PR TITLE
Delete .DS_Store

### PR DESCRIPTION
**Pull request by QiruJin**

### CODE REVIEW

**Review by rickyzhangca — APPROVED** [review]

**Review by cherishfan0320 — APPROVED** [review]
this look right since it is Mac OS might cause conflict.

**Comment by rickyzhangca** [comment]
It has been removed and added to gitignore in dev branch - shouldn't have conflict merging #43 but still causing problems for some reason...let's see if removing it from`master` first and then merge #43

**Comment by QiruJin** [comment]
yeah,,,, sorry to cause this conflict

**Comment by rickyzhangca** [comment]
> yeah,,,, sorry to cause this conflict

no worries there are my commits too, oof

**Review by chengzhen-guo — APPROVED** [review]

**Pull request merged**
