### PR TITLE
test for Landing&Exit

### PR DESCRIPTION
**Pull request by cherishfan0320**
these all finished.

# Pull Request Template

Landing:
test_r1_1 # this test simple landing, unlogged in and valid command
test_r1_2 # this test unlogged in valid command
test_r1_3 # this test log in with valid command and exit
test_r1_4 # this test log in with invalid command and exit

Exit:
test_r7_1 # this test valid command as a simple exit command
test_r7_2 # this test valid login+exit+logout+exit

## Description of Test Case(s)

landing:

## Test Case create for:
- [x] Landing Session
- [ ] Login Session
- [ ] Logout Session
- [ ] Register Session
- [ ] Buy Session
- [ ] Sell Session
- [ ] Update Session
- [x] Exit Session

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit Test
- [ ] Integration Test
- [ ] System Test

## Test Environment:

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

##### Local:

- [x] MacOS
- [ ] Windows

##### IDLE environment:

- [ ] Pycharm
- [x] VScode
- [ ] PythonIDLE
- [x] Others

## Test Case Passed or not:

- [x] Passed
- [ ] Fail

## Description of Source Code

the code works fine, as it match the requirement that invalid/valid command line when user is in different login status.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] More Details about dd comment & change text document

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by chengzhen-guo — APPROVED** [review]

**Review by rickyzhangca — APPROVED** [review]

**Comment by rickyzhangca** [comment]
is the test running for infinitely long time?

**Comment by QiruJin** [comment]
Hey, the Actions shows the Landing Session is failed?

**Comment by QiruJin** [comment]
WOW!!!! all of them passed now!

**Review by QiruJin — APPROVED** [review]

**Comment by cherishfan0320** [comment]
thank god I solve the problem the bug was running me crazy

**Pull request merged**
