### PR TITLE
A2 report

### PR DESCRIPTION
**Pull request by QiruJin**
Write detail test plan in a markdown file

answer the following questions:
-How test cases of different levels (frontend, backend units, integration) are organized. (by Qiru)
-The order of the test cases (which level first which level second). (by Qiru)
-Techniques and tools used for testing. (by Qiru)
-Environemnts (all the local environment and the cloud environment) for the testing. (by Cherish)
-Responsibility (who is responsible for which test case, and in case of failure, who should you contact) (by Cherish)
-Budget Management (you have limited CI action minutes, how to monitor, keep track and minimize unncessary cost) (by Ricky)
-Frontend Architecture (Design & Draw) (by Steven)

### CODE REVIEW

**Review by chengzhen-guo — APPROVED** [review]

**Review by cherishfan0320 — COMMENTED** [review]
All looks good, but is Ricky's Email valid??? It seems a little bit off.
And also we can add the PythonIDLE for testing environment (not necessary) since I am actually using it...

**Comment by rickyzhangca** [comment]
> All looks good, but is Ricky's Email valid??? It seems a little bit off.
> And also we can add the PythonIDLE for testing environment (not necessary) since I am actually using it...

Good good no worries

**Review by rickyzhangca — APPROVED** [review]

**Comment by cherishfan0320** [comment]
> > All looks good, but is Ricky's Email valid??? It seems a little bit off.
> > And also we can add the PythonIDLE for testing environment (not necessary) since I am actually using it...
> 
> Good good no worries

noted.

**Comment by QiruJin** [comment]
> All looks good, but is Ricky's Email valid??? It seems a little bit off.
> And also we can add the PythonIDLE for the testing environment (not necessary) since I am actually using it...

Great Point, added in!

**Comment by chengzhen-guo** [comment]
Hi all,

Frontend architecture diagram has been pushed to a2 branch. In order to have it add to readme, which branch need to be pushed to master.

Please let me know if you have any comment of concern. Thanks!

Happy Programming,
Chengzhen (Steven) Guo

**Review by cherishfan0320 — APPROVED** [review]

**Pull request merged**
