### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by QiruJin**
An initial file of PR Template

### CODE REVIEW

**Review by rickyzhangca — APPROVED** [review]

**Review by chengzhen-guo — APPROVED** [review]

**Comment by rickyzhangca** [comment]
(don't worry about build failure, once #52 is merged it'll pass)

**Comment by QiruJin** [comment]
> (don't worry about build failure, once #52 is merged it'll pass)

That make sense!

**Review by chengzhen-guo — APPROVED** [review]

**Review by cherishfan0320 — APPROVED** [review]
All looks good

**Comment by rickyzhangca** [comment]
I shouldn't have approved this. The path seems incorrect - consider putting the md under `.github` or `docs`. @QiruJin 
image

**Comment by rickyzhangca** [comment]
It's my bad to merge this. @QiruJin  could you move the file and pull again? So that we can use the template. Thx.

**Comment by QiruJin** [comment]
> use

Sure! thanks for discovering this mistake!!!!!!!

**Pull request merged**
