### PR TITLE
add example github actions

### PR DESCRIPTION
**Pull request by rickyzhangca**
an example Workflow, everything's working and passing the tests - but code can be prettier

### CODE REVIEW

**Comment by rickyzhangca** [comment]
sorry I bombed your inboxes

**Comment by QiruJin** [comment]
This is a perfect work! Thanks for this template. (just to make sure, do we need to add a PR template in each PR? )

**Comment by rickyzhangca** [comment]
> This is a perfect work! Thanks for this template. (just to make sure, do we need to add a PR template in each PR? )

thanks and definitely not, otherwise it's not called template

**Review by QiruJin — APPROVED** [review]

**Comment by rickyzhangca** [comment]
image
this thing is beautiful

**Review by cherishfan0320 — APPROVED** [review]

**Review by chengzhen-guo — APPROVED** [review]
Looks good!

**Pull request merged**
