### PR TITLE
adding register session failures to the report

### PR DESCRIPTION
**Pull request by rickyzhangca**
(not using test cases PR template since this is an update to the failure report)

### CODE REVIEW

**Comment by chengzhen-guo** [comment]
Definitly need to work on spelling in the future. Any VS Code plug in could do English spelling check?

**Review by chengzhen-guo — APPROVED** [review]

**Review by QiruJin — APPROVED** [review]
Great explanation! :P

**Comment by QiruJin** [comment]
> Definitly need to work on spelling in the future. Any VS Code plug in could do English spelling check?

We really need such this plug lol!

**Review by cherishfan0320 — APPROVED** [review]
thank you Ricky

**Pull request merged**
