### PR TITLE
More comments/details for code works and report

### PR DESCRIPTION
**Pull request by cherishfan0320**
:P

### CODE REVIEW

**Comment by cherishfan0320** [comment]
Last update the comments for all the code works, thank you guys 🗡️

**Review by QiruJin — APPROVED** [review]
Thanks for the added comment for code, code becomes more readable!

**Review by QiruJin — APPROVED** [review]

**Review by rickyzhangca — APPROVED** [review]

**Comment by cherishfan0320** [comment]
> Thanks for the added comment for code, code becomes more readable!

Thank you Cathy!!!!!!!!!! the report is really nice :D

**Comment by QiruJin** [comment]
> > Thanks for the added comment for code, code becomes more readable!
> 
> Thank you Cathy!!!!!!!!!! the report is really nice :D

You r the first one who said my report is nice!!!!!!!!! (my grammar and writing skill is poor as I know :( ) appreciate your encouragement

**Pull request closed without merging**
