### PR TITLE
functioning register session

### PR DESCRIPTION
**Pull request by rickyzhangca**
re-opened from #41 with new fixes, please review again, thanks

### CODE REVIEW

**Review by chengzhen-guo — APPROVED** [review]

**Comment by QiruJin** [comment]
The code is working well, and more readable than before! the only thing I want to mention is in the 'buy' and 'sell' session,  every invalid input will return to the landing page and need reopen the session again,  is a little bit hard for the user to use, maybe we can optimize it in the future. Overall, we did great work!

**Comment by rickyzhangca** [comment]
added a user name already exists exception to keep exception rising consistent 
https://github.com/rickyzhangca/CISC-327/pull/43/commits/1311718b47bbdcfe2b572d48655f18e6f108cc23
https://github.com/rickyzhangca/CISC-327/pull/43/commits/d8e9bf114e06c447bffaa4d98933d977ae7e02b8

**Comment by chengzhen-guo** [comment]
The code has been cleaned up. Please remember to maintain the comment in your part of the code. And make sure that each feature is working fine.

**Review by QiruJin — APPROVED** [review]
Checked the newest code and working great

**Review by cherishfan0320 — APPROVED** [review]
All looks good！one thing to remember， that landing might only receive specific command when in different login-logout status. Other things looks all good， thank you Ricky！

**Comment by rickyzhangca** [comment]
ds_store is still preventing the merge, hope #46 will help

**Comment by rickyzhangca** [comment]
nice, merged!

**Pull request merged**
