### PR TITLE
Test all transactions when merging into master branch

### PR DESCRIPTION
**Pull request by rickyzhangca**
# Pull Request Template

## Description of Test Case(s)

Please list the test case(s) that you create and corresponding functions. Please also include relevant motivation and context. 

## Test Case create for:
- [ ] Landing Session
- [ ] Login Session
- [ ] Logout Session
- [x] Register Session
- [ ] Buy Session
- [ ] Sell Session
- [ ] Update Session
- [ ] Exit Session

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit Test
- [ ] Integration Test
- [ ] System Test

## Test Environment:

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

##### Local:

- [x] MacOS
- [ ] Windows

##### IDLE environment:

- [ ] Pycharm
- [x] VScode
- [ ] PythonIDLE
- [ ] Others

## Test Case Passed or not:

- [ ] Passed
- [x] Fail

## Description of Source Code

If the source code has been changed. Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] More Details about dd comment & change text document

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rickyzhangca** [comment]
it seems r3 will require some changes

**Comment by rickyzhangca** [comment]
this requires #76 #77 to be able to merge - please approve them, thanks!

**Review by chengzhen-guo — APPROVED** [review]

**Review by cherishfan0320 — APPROVED** [review]
thank you Ricky for all your work! we can never finish this assignment without you!

**Comment by cherishfan0320** [comment]
why the check failed?

**Comment by QiruJin** [comment]
`IndexError: list index out of range` is the error shown in actions! I got this error when I forgot to added the date in ticket info!

**Comment by QiruJin** [comment]
> `IndexError: list index out of range` is the error shown in actions! I got this error when I forgot to added the date in ticket info!

Just noticed all the error happens in R3- the login in one :(

**Comment by rickyzhangca** [comment]
likely need to update the expected outputs

**Review by chengzhen-guo — APPROVED** [review]

**Review by QiruJin — APPROVED** [review]
FINALLY, PASSED!!!!

**Pull request merged**
