### PR TITLE
update details for report, and more comment on code works

### PR DESCRIPTION
**Pull request by cherishfan0320**
thank you guys 👍

### CODE REVIEW

**Comment by QiruJin** [comment]
Thanks for the added comment for code, code becomes more readable right now lol

**Review by QiruJin — APPROVED** [review]

**Review by rickyzhangca — APPROVED** [review]

**Comment by rickyzhangca** [comment]
this is wrapping up the current stage

**Comment by cherishfan0320** [comment]
> Thanks for the added comment for code, code becomes more readable right now lol

nice work on report Cathy！！！：D

**Comment by chengzhen-guo** [comment]
Well done!

**Review by chengzhen-guo — APPROVED** [review]
All comments looks good.

**Pull request merged**
