### PR TITLE
Added design diagram and structure description

### PR DESCRIPTION
**Pull request by chengzhen-guo**
Merged the design diagram into front_end_design.md. Wrote description to illustrate the overall software architecture.

### CODE REVIEW

**Review by QiruJin — APPROVED** [review]
The structure is soooo clear and intuitive! I think this file includes all classes and functions we use in SeekGeek.

**Review by rickyzhangca — APPROVED** [review]
Looks good to me.

**Comment by QiruJin** [comment]
I have added a description of `buySession` and `sellSession` in front_end_design

**Comment by QiruJin** [comment]
During we added the description of `Register`, `landing`, `login1, `logout`, `buy`, `sell`, `update`, the front_end_design is more complete and much better!

**Review by cherishfan0320 — APPROVED** [review]
All looks good. Thank you for your work Steven!

**Comment by rickyzhangca** [comment]
merged!!

**Pull request merged**
